name: CI
on:
  push:
    branches:
      - main
    tags: '*'
  pull_request:
concurrency:
  # Skip intermediate builds: always.
  # Cancel intermediate builds: only if it is a pull request build.
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}
jobs:
  docs:
    name: Documentation
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
        - uses: actions/checkout@v3
        - uses: julia-actions/setup-julia@v1
          with:
            version: '1'
        - uses: actions/cache@v3
          with:
            path: |
              ~/.julia/artifacts
              ~/.julia/packages
              ~/.julia/registries
            key: .julia-docs-${{ hashFiles('docs/Project.toml', 'docs/Manifest.toml') }}
        - name: Install dependencies
          run: |
            julia --color=yes --project=docs -e '
            using Pkg
            packages = [
                PackageSpec(;url="https://github.com/KnutAM/MaterialModelsBase.jl.git"),
                PackageSpec(;url="https://github.com/lijas/IGA.jl.git"),
                PackageSpec(path=pwd())
                ]
            Pkg.develop(packages)
            Pkg.instantiate()'
            shell: bash
        - name: Build and deploy
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            DOCUMENTER_KEY: ${{ secrets.DOCUMENTER_KEY }}
            GKSwstype: '100'
          run: julia --project=docs --color=yes docs/make.jl
