name: CI
on:
  push:
    branches:
      - main
    tags: '*'
  pull_request:
concurrency:
  # Skip intermediate builds: always.
  # Cancel intermediate builds: only if it is a pull request build.
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}
jobs:
  docs:
    name: Documentation
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@v1
        with:
          version: '1'
      # - uses: julia-actions/julia-buildpkg@v1
      - run: |
          julia --color=yes --project=docs -e '
            using Pkg
            packages = [
              PackageSpec(;url="https://github.com/KnutAM/MaterialModelsBase.jl.git"),
              PackageSpec(;url="https://github.com/lijas/IGA.jl.git"),
              PackageSpec(path=pwd())
              ]
            Pkg.develop(packages)
            Pkg.instantiate()'
        shell: bash
      - uses: julia-actions/julia-docdeploy@v1
        with:
          install-package: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DOCUMENTER_KEY: ${{ secrets.DOCUMENTER_KEY }}
      - run: |
          julia --project=docs -e '
            using Documenter: DocMeta, doctest
            using FerriteAssembly
            DocMeta.setdocmeta!(FerriteAssembly, :DocTestSetup, :(using FerriteAssembly); recursive=true)
            doctest(FerriteAssembly)'
