name: FerriteMasterCI
on:
  schedule:
  - cron: '0 4 * * 2' # 04:00 UTC every monday
  push:
    branches:
      - main
    tags: '*'
  pull_request:
concurrency:
  # Skip intermediate builds: always.
  # Cancel intermediate builds: only if it is a pull request build.
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}
jobs:
  test:
    name: Julia ${{ matrix.version }} - ${{ matrix.os }} - ${{ matrix.arch }} - ${{ github.event_name }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 15
    strategy:
      fail-fast: false
      matrix:
        version:
          - '1'
        os:
          - ubuntu-latest
        arch:
          - x64
    steps:
      - uses: actions/checkout@v4
      - uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}
      - uses: julia-actions/cache@v1
      # - uses: julia-actions/julia-buildpkg@v1   # Replaced by the following
      - run: |
          julia --color=yes --project=. -e '
            using Pkg
            packages = [
              PackageSpec(;url="https://github.com/Ferrite-FEM/Ferrite.jl.git", rev="master"),
              PackageSpec(;url="https://github.com/KnutAM/MaterialModelsBase.jl.git"),
              ]
            Pkg.add(packages)
            Pkg.instantiate()'
        shell: bash
      - uses: julia-actions/julia-runtest@v1
